import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
// import classNames from 'classnames'


export default function Home() {
  // toggle_box_question
  const [showMe1, setShowMe1] = useState(false);
  const [showMe2, setShowMe2] = useState(false);
  const [showMe3, setShowMe3] = useState(false);
  const [showMe4, setShowMe4] = useState(false);
  function toggle_box_question1() {
    setShowMe1(!showMe1)
  }
  function toggle_box_question2() {
    setShowMe2(!showMe2)
  }
  function toggle_box_question3() {
    setShowMe3(!showMe3)
  }
  function toggle_box_question4() {
    setShowMe4(!showMe4)
  }
  // toggle_hover_date
  const [toggleHover1, setToggleHover1] = useState(false)
  const [toggleHover2, setToggleHover2] = useState(false)
  const [toggleHover3, setToggleHover3] = useState(false)
  const [toggleHover4, setToggleHover4] = useState(false)
  function toggle_hover_date1() {
    setToggleHover1(!toggleHover1)
  }
  function toggle_hover_date2() {
    setToggleHover2(!toggleHover2)
  }
  function toggle_hover_date3() {
    setToggleHover3(!toggleHover3)
  }
  function toggle_hover_date4() {
    setToggleHover4(!toggleHover4)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Nft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* Font GG */}
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;400;500;600&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet"/>
      </Head>

      <main  className={styles.main}>
        <section id='main'></section>
        <div className={styles.banner}>
          <div className={styles.nav}>
            <ul className={styles.nav_left}>
              <li><a href='#our_Vision'>Introduction</a></li>
              <li><a href='#Ecosystem'>Ecosystem</a></li>
              <li><a href='#pre_Sale'>Pre-sale</a></li>
              <li><a href='#our_Features'>Tokenomic</a></li>
            </ul>
            <ul className={styles.nav_right}>
              <li><a href='#road_Map'>Roadmap</a></li>
              <li><a href=''>White Paper</a></li>
              <li><a href=''>Partners</a></li>
              <button><a>Connect</a></button>
            </ul>         
          </div>
          <div className={styles.animation_earth}>
          {/* banner-left */}
            <div className={styles.banner_left}>
              <img
                className={styles.vector}
                src='/Vector-1.png'
              />
              <img
                className={styles.group37108}
                src='/Group 37108.png'
              />
              <img
                className={styles.Rectangle175}
                src='/Rectangle 175.png'
              />
              <img
                className={styles.Rectangle177}
                src='/Rectangle 177.png'
              />
              <img
                className={styles.Rectangle171}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Rectangle171_2}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Rectangle171_3}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Rectangle171_4}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Rectangle171_5}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Rectangle171_6}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Rectangle171_7}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Rectangle171_8}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Rectangle171_9}
                src='/Rectangle 171.png'
              />
              <img
                className={styles.Ellipse11}
                src='/Ellipse 11.png'
              />
              <img
                className={styles.Rectangle174}
                src='/Rectangle 174.png'
              />
              <img
                className={styles.Ellipse13}
                src='/Ellipse 13.png'
              />
              <img
                className={styles.Rectangle176}
                src='/Rectangle 176.png'
              />
              <img
                className={styles.png4}
                src='/4.png'
              />
              <img
                className={styles.Ellipse16}
                src='/Ellipse 16.png'
              />
              <img
                className={styles.Frame4}
                src='/frame_4.png'
              />
              <img
                className={styles.Frame11}
                src='/frame_11.png'
              />
              <img
                className={styles.group37109}
                src='/Group 37109.png'
              />
              <img
                className={styles.mdi_star_four_points}
                src='/mdi_star_four_points.png'
              />
              <img
                className={styles.mdi_star_four_points_2}
                src='/mdi_star_four_points_2.png'
              />
              <img
                className={styles.Ellipse14}
                src='/Ellipse 14.png'
              />
              <img
                className={styles.Frame2}
                src='/frame_2.png'
              />
              <img
                className={styles.Ellipse21}
                src='/Ellipse 21.png'
              />
              <img
                className={styles.Ellipse19}
                src='/Ellipse 19.png'
              />
              <img
                className={styles.Planet_8_1}
                src='/Planet-10.png'
              />
              <img
                className={styles.Planet_13}
                src='/Planet_13.png'
              />
              <img
                className={styles.Ellipse17}
                src='/Ellipse 17.png'
              />
              <img
                className={styles.Frame9}
                src='/frame_9.png'
              />
              <img
                className={styles.Ellipse23}
                src='/Ellipse 23.png'
              />
              <img
                className={styles.Vector_8}
                src='/Vector-8.png'
              />
              <img
                className={styles.Frame5}
                src='/frame_5.png'
              />
              <img
                className={styles.Rectangle173}
                src='/Rectangle 173.png'
              />
              <img
                className={styles.Ellipse22}
                src='/Ellipse 22.png'
              />
              <img
                className={styles.Ellipse12}
                src='/Ellipse 12.png'
              />
            </div>
            {/* banner center */}
            <div className={styles.banner_center}>
              <img
                className={styles.Ellipse10}
                src='/Ellipse 10.png'
              />
              <img
                className={styles.Ellipse9}
                src='/Ellipse 9.png'
              />
              <div className={styles.Frame_earth}>

              </div>
              <img
                className={styles.Frame}
                src='/Frame.png'
              />
              <div className={styles.content_banner}>
                <h1>DoWork</h1>
                  <p>LAIKA INU FINANCE is being developed as a Decentralized Eco-System with a LaunchPad, Farming, Staking, NFT Marketplace, and a Metaverse on Binance Smart Chain.</p>
              </div>
            </div>
            {/* banner-right */}
            <div className={styles.banner_right}>
              <img
                className={styles.mdi_star_four_points_1}
                src='/mdi_star_four_points_1.png'
              />
              <img
                className={styles.mdi_star_four_points_1_1}
                src='/mdi_star_four_points_1.png'
              />
              <img
                className={styles.mdi_star_four_points_1_2}
                src='/mdi_star_four_points_1.png'
              />
              <img
                className={styles.mdi_star_four_points_1_3}
                src='/mdi_star_four_points_1.png'
              />
              <img
                className={styles.Vector_15}
                src='/Vector-15.png'
              />
              <img
                className={styles.Vector_16}
                src='/Vector-16.png'
              />
              <img
                className={styles.Planet_1}
                src='/Planet_1.png'
              />
              <img
                className={styles.Frame_7}
                src='/Frame_7.png'
              />
              <img
                className={styles.Frame_8}
                src='/Frame_8.png'
              />
              <img
                className={styles.Frame_3}
                src='/Frame_3.png'
              />
              <img
                className={styles.Rectangle179}
                src='/Rectangle 179.png'
              />
              <img
                className={styles.Ellipse24}
                src='/Ellipse 14.png'
              />
              <img
                className={styles.Ellipse4}
                src='/Ellipse 4.png'
              />
              <img
                className={styles.mdi_star_four_points_1_4}
                src='/mdi_star_four_points_1.png'
              />
              <img
                className={styles.mdi_star_four_points_1_5}
                src='/mdi_star_four_points_1.png'
              />
              <img
                className={styles.Planet_8}
                src='/Planet-10.png'
              />
              <img
                className={styles.Ellipse18}
                src='/Ellipse 18.png'
              />
              <img
                className={styles.mdi_star_four_points_1_6}
                src='/mdi_star_four_points_1.png'
              />
              <img
                className={styles.png1}
                src='/1.png'
              />
              <img
                className={styles.Ellipse15}
                src='/Ellipse 15.png'
              />
              <img
                className={styles.Vector_6}
                src='/Vector-6.png'
              />
              <img
                className={styles.Vector_7}
                src='/Vector-7.png'
              />
              <img
                className={styles.Frame_1}
                src='/frame_1.png'
              />
              <img
                className={styles.mdi_star_four_points_2_1}
                src='/mdi_star_four_points_2.png'
              />
            </div>
            {/* banner bottom */}
            <div className={styles.banner_bottom}>
              <img
                className={styles.Vector_9}
                src='/Vector-9.png'
              />
              <img
                className={styles.Ellipse20}
                src='/Ellipse 20.png'
              />
              <img
                className={styles.Rectangle172}
                src='/Rectangle 172.png'
              />
              <img
                className={styles.Ellipse12_1}
                src='/Ellipse 12-1.png'
              />
              <img
                className={styles.Ellipse21_1}
                src='/Ellipse 20.png'
              /> 
              <img
                className={styles.Ellipse22_1}
                src='/Ellipse 20.png'
              /> 
              <img
                className={styles.Rectangle171_1}
                src='/Rectangle 179(1).png'
              />
            </div>
          </div> 
        </div>
        <div id='our_Vision' className={styles.our_Vision}>
          <div className={styles.content}>
            <div className={styles.img_Vision}>
              <img
                className={styles.Frame_13}
                src='/Frame_13.png'
              />
              <img
                className={styles.Frame_12}
                src='/Frame_12.png'
              />
            </div>
            <div className={styles.content_Vision}>
              <h1><b className={styles.b}>OUR</b> VISION</h1>
              <span>Traditional finance doesn’t work. For too long it’s been serving the wealthy suits while erecting barriers of entry for everyone else. They own the data, restrict the tools, and change the rules to always be in their favor. It’s time to not only give that power back to the people, but to create even more powerful tools that the old cumbersome system could
              <br></br>
              At <b>LAIKA INU FINANCE</b>, we’re building a community composed of brilliant minds all seeking control of their own finances and building a new system that works for everyone. Synthetic assets allow us to create financial instruments and markets never seen before. If the data exists, so too can a marketplace for it - the possibilities are endless.
              It all comes down to data. Most people aren’t aware that financial data is what makes institutions so powerful and why you can’t do what they do. This is why synthetics will matter. If you can get liquidity in any discrete quantifiable event, what have you created? The world’s most accurate financial data system. Financial data is used within insurance, lending, hedge funds, risk mitigation, banking, yield, mortgages, credit scores, etc.
                Incentivised synthetics allow you to start building an open financial data market. Once you have synthetics, you own the financial data stream to anything because you can incentivise liquidity to make it more accurate. With this financial data stream you can start any DeFi business you want on top of it, or package and sell the data for others to build on. You become the foundation for the future of finance
              </span>
              <div className={styles.about_Vision}>
                <div className={styles.Unlimited}>
                  <img
                    className={styles.icon_left}
                    src='/uil_chart-down-1.png'
                  />
                  <p>Unlimited</p>
                </div>
                <div className={styles.Global}>
                  <img
                    className={styles.icon_right}
                    src='/global_icon.png'
                  />
                  <p>Global</p>
                </div>
                <div className={styles.Multi_platform}>
                  <img
                    className={styles.icon_left}
                    src='/muti_platform_icon.png'
                  />
                  <p>Multi-platform</p>
                </div>
                <div className={styles.Meta_work}>
                  <img
                    className={styles.icon_right}
                    src='/Meta work_icon.png'
                  />
                  <p>Meta work</p>
                </div>
              </div>
            </div>
          </div>
          <div id='Ecosystem' className={styles.Ecosystem}>
            <div className={styles.Ecosystem_left}>
              <h1>ECOSYSTEM</h1>
              <p>LAIKA INU FINANCE aims to build an efficient, circular ecosystem that brings together the best resources-from mainstream financial products to breakthrough technology applications-to maximize value.</p>
              <span>Laika Decentralized Eco-System</span>
              <div className={styles.Ecosystem_Laika}>
                <div className={styles.list_Laika}>
                  <div className={styles.Laika_Wallet}>
                    <img
                      className={styles.list_Laika_left}
                      src='/Filled Success.svg'
                    />
                    Laika Wallet
                  </div>
                  <div className={styles.Laika_Auto_Staking}>
                    <img
                      className={styles.list_Laika_right}
                      src='/Filled Success.svg'
                    />
                    Laika Auto Staking
                  </div>
                  <div className={styles.Laika_Lauchpad}>
                    <img
                      className={styles.list_Laika_left}
                      src='/Filled Success.svg'
                    />
                    Laika Lauchpad
                  </div>
                  <div className={styles.Laika_Lottery}>
                    <img
                      className={styles.list_Laika_right}
                      src='/Filled Success.svg'
                    />
                    Laika Lottery
                  </div>
                  <div className={styles.LaikaNFT_Marketplace}>
                    <img
                      className={styles.list_Laika_left}
                      src='/Filled Success.svg'
                    />
                    LaikaNFT Marketplace
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id='our_Features' className={styles.our_Features}>
          <h1><b className={styles.b}>OUR</b> FEATURES</h1>
          <div className={styles.list_features}>
            <div className={styles.box_features_Unlimited}>
              <div className={styles.content_features}>
                <img
                  src='uil_chart-down.png'
                />
                <h4>Unlimited</h4>
                <div className={styles.content_features_1}>
                  <p>t’s easy, fair, and you can enter as often as you like as long as you have the $LAKA to buy a ticket. The Laika Lottery is a game of chance in which winners are selected randomly. Our ottery allows  </p>
                </div>
                <div className={styles.content_features_2}>
                  <p>
                    user who bought at least one lottery ticket to get rewarded with huge $LAKA prizes.
                  </p>
                </div>
              </div>
            </div>
            <div className={styles.box_features_Global}>
              <div className={styles.content_features}>
                <img
                  src='Global_1.png'
                />
                <h4>Global</h4>
                <div className={styles.content_features_1}>
                  <p>t’s easy, fair, and you can enter as often as you like as long as you have the $LAKA to buy a ticket. The Laika Lottery is a game of chance in which winners are selected randomly. Our ottery allows  </p>
                </div>
                <div className={styles.content_features_2}>
                  <p>
                    user who bought at least one lottery ticket to get rewarded with huge $LAKA prizes.
                  </p>
                </div>
              </div>
            </div>
            <div className={styles.box_features_Multi}>
              <div className={styles.content_features}>
                <img
                  src='carbon_iot-platform.png'
                />
                <h4>Multi-platform</h4>
                <div className={styles.content_features_1}>
                  <p>t’s easy, fair, and you can enter as often as you like as long as you have the $LAKA to buy a ticket. The Laika Lottery is a game of chance in which winners are selected randomly. Our ottery allows  </p>
                </div>
                <div className={styles.content_features_2}>
                  <p>
                    user who bought at least one lottery ticket to get rewarded with huge $LAKA prizes.
                  </p>
                </div>
              </div>
            </div>
            <div className={styles.box_features_Meta}>
              <div className={styles.content_features}>
                <img
                  src='meta.png'
                />
                <h4>Meta work</h4>
                <div className={styles.content_features_1}>
                  <p>t’s easy, fair, and you can enter as often as you like as long as you have the $LAKA to buy a ticket. The Laika Lottery is a game of chance in which winners are selected randomly. Our ottery allows  </p>
                </div>
                <div className={styles.content_features_2}>
                  <p>
                    user who bought at least one lottery ticket to get rewarded with huge $LAKA prizes.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id='pre_Sale' className={styles.pre_Sale}>
          <div className={styles.title_sale}>
            <h2>PRE-SALE</h2>
            <h5>Pre-sale is live</h5>
          </div>
          <div className={styles.exchange_Token}>
            <div className={styles.buy_Token}>
              <div className={styles.buy_Token_bg}>
                <h4>BUY TOKEN</h4>
                <p>Become we holder of the token and get access to the pre-sale</p>
                <div className={styles.exchange_Token_text}>
                  <img
                    src='Filled Success.png'
                  />
                  <p1>10 BNB = 200.000.000 LAKA</p1>
                </div>
                <div className={styles.exchange_Token_text}>
                  <img
                    src='Filled Success.png'
                  />
                  <p1>1 BNB = 20.000.000 LAKA</p1>
                </div>
                <div className={styles.exchange_Token_text}>
                  <img
                    src='Filled Success.png'
                  />
                  <p1>Claim 80.000 LAKA</p1>
                </div>
                <div className={styles.box_input_token}>
                  <input maxlength="10" type='number' className='h-14 pl-6'>
                  </input>
                  <div className={styles.input_right}>
                    <p2>BNB</p2>
                    <button className={styles.add_Wallet}>+ Add Wallet</button>
                  </div>
                </div>
                <div className='flex justify-center mt-5 btn_buy_Token'>
                  <button className='flex'>
                    <img src='Vector_buy_token.png'/>Buy Token
                  </button>
                </div>
              </div>
            </div>
            <div className={styles.get_Airdrop}>
              <div className={styles.get_Airdrop_bg}>
                <h4>GET AIRDROP</h4>
                <p>After fulfilling chores for the appropriate number of days, you can receive airdrops.</p>
                <div className={styles.get_Airdrop_free}>
                  <img
                    src='Filled Success.png'
                  />
                  <p1>On the free plan, you can get airdrops after completing activities for 7 days in a row.</p1>
                </div>
                <div className={styles.get_Airdrop_free}>
                  <img
                    src='Filled Success.png'
                  />
                  <p1>When you improve your account plan, you can shorten the time it takes to get airdrops.</p1>
                </div>
                <div className='flex justify-center mt-5 btn_claim_now'>
                  <button className='flex'>
                    <img src='bx_gift.png'/>CALIM NOW
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id='question' className='question flex justify-between'>
          <div className='question_left'>
            <div className='title_question'>
              <h1><b className={styles.b}>FRENQUENTLY</b> QUESTION</h1>
              <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis accumsan nisi Utut felis congue nisl hendrerit commodo</span>
              <img src='2106.w013.n001.474B.p30 1.png'/>
            </div>
          </div>
          
          <div className='question_right'>
            {/* onClick={toggle_box_question} */}
            <div className='box_question'>
              <h2 onClick={toggle_box_question1}>What are the objectives of this Token?</h2>
              <p style={{display: showMe1?"block":"none"}}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore omnis quaerat nostrum, pariatur ipsam sunt accusamus enim necessiatibus est fugiat, assumenda dolorem, delenti corrupti cupiditate ipsum, dolorum voluptatum esse error?</p>
            </div>
            <div className='box_question'>
              <h2 onClick={toggle_box_question2}>What is the best features and services we deiver?</h2>
              <p style={{display: showMe2?"block":"none"}}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore omnis quaerat nostrum, pariatur ipsam sunt accusamus enim necessiatibus est fugiat, assumenda dolorem, delenti corrupti cupiditate ipsum, dolorum voluptatum esse error?</p>
            </div>
            <div className='box_question'>
              <h2 onClick={toggle_box_question3}>Why this ICO important to me?</h2>
              <p style={{display: showMe3?"block":"none"}}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore omnis quaerat nostrum, pariatur ipsam sunt accusamus enim necessiatibus est fugiat, assumenda dolorem, delenti corrupti cupiditate ipsum, dolorum voluptatum esse error?</p>
            </div>
            <div className='box_question'>
              <h2 onClick={toggle_box_question4}>How may I take part in and purchase this Token?</h2>
              <p style={{display: showMe4?"block":"none"}}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore omnis quaerat nostrum, pariatur ipsam sunt accusamus enim necessiatibus est fugiat, assumenda dolorem, delenti corrupti cupiditate ipsum, dolorum voluptatum esse error?</p>
            </div>
          </div>
        </div>
        <div id='token_Diagram' className='token_Diagram flex'>
          <div className='title_Token'>
            <h2>TOKEN</h2>
            <span className='pb-4'>distribution</span>
            <p>Name: Laika Inu Finance</p>
            <p>Symbol: <b>NFT</b></p>
            <p>Decimails: 18</p>
            <p className='pb-2.5'>1 NFT = 0.000045$</p>
            <p>Smart Contract:</p>
            <p className='pb-2.5'>0xF71142E892226E56719EBb3Ac0776dBbDf3918</p>
            <p>Total Supply: <b>200,000,000,000</b></p>
            <p>Network: Binance Smart Chain</p>
          </div>
          <div className='w-3/6 text-center diagram'>
            {/* <div className='text_percent percent_Development'>
              <b>55%</b>
              <p>For IT<br></br>Development</p>
            </div>
            <div className='text_percent percent_Maketing'>
              <b>10%</b>
              <p>Sale and<br></br>Maketing</p>
            </div>
            <div className='text_percent percent_Parterships'>
              <b>5%</b>
              <p>Accession and<br></br>Parterships</p>
            </div>
            <div className='text_percent percent_Partners'>
              <b>15%</b>
              <p>Admin and<br></br>Partners</p>
            </div>
            <div className='text_percent percent_Financial'>
              <b>20%</b>
              <p>Legal and<br></br>Financial</p>
            </div> */}
            <img src='Group 37120.png'/>
          </div>
          <div className='note_colors w-2/6 grid grid-cols-2 gap-2'>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 96.png' />
              <p><b>Token Name</b><br></br>Crypto Token</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 101.png' />
              <p><b>Token Name</b><br></br>Crypto Token</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 97.png' />
              <p><b>ICO Pre-sale starts in</b><br></br>June 15-30, 2022</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 102.png' />
              <p><b>ICO Pre-sale starts in</b><br></br>June 15-30, 2022</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 98.png' />
              <p><b>Platform</b><br></br>June 15-30, 2022</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 103.png' />
              <p><b>Platform</b><br></br>June 15-30, 2022</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 99.png' />
              <p><b>PreICO price</b><br></br>June 15-30, 2022</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 104.png' />
              <p><b>PreICO price</b><br></br>June 15-30, 2022</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 100.png' />
              <p><b>Price in ICO</b><br></br>1 ETF = 2,182 Token</p>
            </div>
            <div className='flex flex-row items-center h-12'>
              <img className='h-7 w-7 mr-2.5' src='Ellipse 105.png' />
              <p><b>Price in ICO</b><br></br>1 ETF = 2,182 Token</p>
            </div>
          </div>
        </div>
        <div id='road_Map' className='road_Map'>
          <h2>ROADMAP</h2>
          <span >Our Strategy & Project Plan</span>
          <h4 className='text-center'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed quis accumsan nisi Ut ut felis congue nisl hendrerit commodo </h4>
          <div className='flex'>
            <div className=' road_Map_left w-6/12'>
              <div onMouseEnter={toggle_hover_date1} 
                onMouseLeave={toggle_hover_date1} 
                className='date_plan_left'>
              
                <p className='text-sm'>22 Sept</p>
                <div className='date_split_left'></div>
                <b className=''>2021</b>
                <div className='date_plan_left_shadow'></div>
              </div>
              
              <div className='strategy_left text-lg'>
                Plaform integration to marketplaces
                <h5 className='text-sm'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur ex sit amet massa scelerisque scelerisque. Aliquam erat volutpat. Aenean interdum finibus eficitur. Praesent dapibus dolor felis, eu ultrices elit molestie</h5>
              </div>
              <div onMouseEnter={toggle_hover_date2} 
                onMouseLeave={toggle_hover_date2}
                className='date_plan_left text-center'>
                <p>27 Nov</p>
                <div className='date_split_left'></div>
                <b>2021</b>
                <div className='date_plan_left_shadow'></div>
              </div>
              <div className='strategy_left text-lg'>
                Plaform ealier version development
                <h5 className='text-sm'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur ex sit amet massa scelerisque scelerisque. Aliquam erat volutpat. Aenean interdum finibus eficitur. Praesent dapibus dolor felis, eu ultrices elit molestie</h5>
              </div>
            </div>
            <div className='map_Split1 flex'>
              <div className='dot_split_y_1'>
                <img className={`dot_y_1${toggleHover1 ? ' dot_y_hover_1' : ''}`} src='Ellipse 107.png'/>
              </div>
              <div className='dot_split_shadow_2'>
                <img className='dot_shadow_2' src='Ellipse 106.png'/>
              </div>
              <div className='dot_split_y_3'>
                <img className={`dot_y_3${toggleHover2 ? ' dot_y_hover_3' : ''}`} src='Ellipse 107.png'/>
              </div>
              <div className='dot_split_shadow_4'>
                <img className='dot_shadow_4' src='Ellipse 106.png'/>
              </div>
              <div className='map_Split'></div>
              <div className='dot_split_shadow_1'>
                <img className='dot_shadow_1' src='Ellipse 106.png'/>
              </div>
              <div className='dot_split_y_2'>
                <img className={`dot_y_2${toggleHover3 ? ' dot_y_hover_2' : ''}`} src='Ellipse 107.png'/>
              </div>
              <div className='dot_split_shadow_3'>
                <img className='dot_shadow_3' src='Ellipse 106.png'/>
              </div>
              <div className='dot_split_y_4'>
                <img className={`dot_y_4${toggleHover4 ? ' dot_y_hover_4' : ''}`} src='Ellipse 107.png'/>
              </div>
            </div>
            <div className='road_Map_right w-6/12'>
              <div className='strategy_right text-lg'>
                Listing to the major exchanges
                <h5 className='text-sm'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur ex sit amet massa scelerisque scelerisque. Aliquam erat volutpat. Aenean interdum finibus eficitur. Praesent dapibus dolor felis, eu ultrices elit molestie</h5>
              </div>
              <div onMouseEnter={toggle_hover_date3} 
                onMouseLeave={toggle_hover_date3}
                className='date_plan_right text-center'>
                <p>22 Sept</p>
                <div className='date_split_right'></div>
                <b>2021</b>
                <div className='date_plan_right_shadow'></div>
              </div>
              <div className='strategy_right text-lg'>
                Crypto Wallet version release
                <h5 className='text-sm'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed efficitur ex sit amet massa scelerisque scelerisque. Aliquam erat volutpat. Aenean interdum finibus eficitur. Praesent dapibus dolor felis, eu ultrices elit molestie</h5>
              </div>
              <div onMouseEnter={toggle_hover_date4} 
                onMouseLeave={toggle_hover_date4}
                className='date_plan_right text-center'>
                <p>27 Nov</p>
                <div className='date_split_right'></div>
                <b>2021</b>
                <div className='date_plan_right_shadow'></div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className=''>
        <img src='Frame-11.png' />
        <h4>DO WORK -Decentralized financial system</h4>
      </footer>
      
    </div>
  )
}
